solve pe109

diff --git a/Cpp/run b/Cpp/run
--- a/Cpp/run
+++ b/Cpp/run
@@ -5,6 +5,10 @@
 filename=$(basename "$1")
 executable="${filename%.*}".out
 
+# prevent possible overwrite
+[ -f "$executable" ] &&
+    printf "\033[1;31m*** Naming Conflict ***\033[1m\n" && exit 1
+
 # make sure mathutil is up to date
 LIBRARY="mathutil.o"
 LIB_HDR="mathutil.h"
@@ -16,7 +20,7 @@ then
     make -s
     # if library does not make successfully
     if [ $? -ne 0 ]; then
-        printf "\033[0;31m*** FAIL TO COMPILE LIBRARY ***\033[0m\n"
+        printf "\033[1;31m*** FAIL TO COMPILE LIBRARY ***\033[1m\n"
         exit 1
     fi
     g++ -o "$executable" "$filename" $LIBRARY -std=c++11 -O2
@@ -25,7 +29,7 @@ else
 fi
 
 if [ $? -ne 0 ]; then
-    printf "\033[0;31m*** FAIL TO COMPILE %s ***\033[0m\n" "$filename"
+    printf "\033[1;31m*** FAIL TO COMPILE %s ***\033[1m\n" "$filename"
     exit 1
 fi
 
