solve new problem

diff --git a/Cpp/run b/Cpp/run
--- a/Cpp/run
+++ b/Cpp/run
@@ -2,34 +2,33 @@
 
 # run a specific cpp file and time it
 
-filename=$(basename $1)
+filename=$(basename "$1")
 executable="${filename%.*}".out
 
 # make sure mathutil is up to date
 LIBRARY="mathutil.o"
 LIB_HDR="mathutil.h"
 
-make -s
-
-# if library does not make successfully
-if [ $? -ne 0 ]; then
-    echo "*** FAIL TO COMPILE LIBRARY ***"
-    exit 1
-fi
 
 # check whether source file need LIBRARY
-if grep "^#include\s*\"$LIB_HDR\"\s*$" $filename > /dev/null
+if egrep "^#include\s*\"$LIB_HDR\"" "$filename" > /dev/null
 then
-    g++ -o $executable $filename $LIBRARY -std=c++11 -O2
+    make -s
+    # if library does not make successfully
+    if [ $? -ne 0 ]; then
+        printf "\033[0;31m*** FAIL TO COMPILE LIBRARY ***\033[0m\n"
+        exit 1
+    fi
+    g++ -o "$executable" "$filename" $LIBRARY -std=c++11 -O2
 else
-    g++ -o $executable $filename -std=c++11 -O2
+    g++ -o "$executable" "$filename" -std=c++11 -O2
 fi
 
 if [ $? -ne 0 ]; then
-    echo "*** FAIL TO COMPILE $filename ***"
+    printf "\033[0;31m*** FAIL TO COMPILE %s ***\033[0m\n" "$filename"
     exit 1
 fi
 
 echo "running $executable"
-time ./$executable
-rm $executable
+time ./"$executable"
+rm "$executable"
